### ISSUE TITLE
Permission to clone?

### ISSUE THREAD

**Issue by d8ahazard** [Aircoookie/WLED-App#12]
Hey again!

So, my ongoing project that interacts with WLED also features a device that is discoverable over the network via MDNS, and can be controlled via an embedded web UI.

As such, I copied the WLED app code and hacked it to work with my device. I still need to implement the proper api for mode and brightness...but for the most part, I've already got it working.

But, before I get too far, I just wanted to ask permission to use your app as a starting point for my own. I'll obviously remove all the WLED branding and links and stuff - but mention in the modded git that yours is the source. And hell, I might be able to submit some PRs for the original app too to update the xamarin version and other stuff.

TIA!

**Comment by ErrorErrorError** [comment]
As far as MIT goes, you're allowed to clone it and create your own

**Comment by Aircoookie** [comment]
Exacltly, feel free to :)

**Comment by d8ahazard** [comment]
> Exacltly, feel free to :)

Much appreciated! It was much less about the license, and more about showing a bit of respect for the awesome ecosystem you've built. :D
