### ISSUE TITLE
Is this project abandoned? No updates since 2019

### ISSUE THREAD

**Issue by Jefte** [Aircoookie/WLED-App#15]
Is this repo abandoned or has someone else forked this project elsewhere? No updates to the android app since 2019 and there is still a huge bug when powering on/off units.

**Comment by Aircoookie** [comment]
Hey!

Yes, this is mostly abandoned.
My focus is 100% on the main project currently.
I hope to be able to offer a better native app at some point, but I'm not sure if or when I'll have the time. Sorry about that.

**Comment by Aircoookie** [comment]
Where have you reported the bug when powering on/off though?
While I'm not currently adding new features, I am still trying to keep the basic functionality alive and have this app provide a good experience for managing multiple devices.

**Comment by Jefte** [comment]
Ok thanks for the info! 

When turning strips on/off using the android app, the color often defaults to an orange. Then I must tap one of my presets to load the desired preset.

Annoying to be sure, but technically the app still works. Thanks for your effort maintaining this.
