### ISSUE TITLE
Starting Discovery on Android 13 force closes app

### ISSUE THREAD

**Issue by flipside101** [Aircoookie/WLED-App#23]
App force closes when I hit the discovery button since I updated to Android 13 , adding manually works as done the rest of the app

Pixel 6 running Android 13
Latest version of WLED app
Data and cache cleared and reinstalled app

**Comment by Gnat5680** [comment]
Also having the same issue. I thought it was just my device and tried the same steps with no success. Appears to be related to the Android 13 update.

**Comment by chrismeg** [comment]
Also having this issue on both a Pixel 4a XL and a Pixel 6 both running Android 13

**Comment by Tomasin76** [comment]
is there a solution to this issue?

**Comment by mattgrooms** [comment]
As well on my Pixel 6A & Android 13

**Comment by KnuckleUpFPV** [comment]
Same issue on s22 ultra. My s20 works because it hasn't updated to 13 I guess.

**Comment by gamer1966** [comment]
@Aircoookie: please change "<AndroidSupportedAbis>armeabi;armeabi-v7a;x86;x86_64;arm64-v8a</AndroidSupportedAbis>" to "<AndroidSupportedAbis>armeabi-v7a;x86;x86_64;arm64-v8a</AndroidSupportedAbis>" (delete "armeabi;") in WLED.Android.csproj.

Update Your Visual Studio ( I think it's already done over the years) and rebuild WLED-App.

After this no more closing the app under Android 13 when discovering lights.

**Comment by KnuckleUpFPV** [comment]
Will this change be done to the app store version? I believe that's where most get their app from.

**Comment by nickdevore** [comment]
I tried testing this myself but honestly was not successful in testing it.  Can someone else test it? #27

**Comment by Moustachauve** [comment]
It is self promotion, but you can use my version of the app, WLED Native, to solve the discovery on android

https://play.google.com/store/apps/details?id=ca.cgagnier.wlednativeandroid
https://github.com/Moustachauve/WLED-Native-Android

**Comment by KnuckleUpFPV** [comment]
> It is self promotion, but you can use my version of the app, WLED Native, to solve the discovery on android
> 
> https://play.google.com/store/apps/details?id=ca.cgagnier.wlednativeandroid https://github.com/Moustachauve/WLED-Native-Android

I'm happy to use your version if it works. I'll test tonight. Thank you for this!

**Comment by KnuckleUpFPV** [comment]
> It is self promotion, but you can use my version of the app, WLED Native, to solve the discovery on android
> 
> https://play.google.com/store/apps/details?id=ca.cgagnier.wlednativeandroid https://github.com/Moustachauve/WLED-Native-Android

This worked fantastically. Better than the regular app. I could be on any wifi in my network and find the devices instantly. Unlike the original app that would take a while before it stopped working on the new android update. Thanks again!

**Comment by JTWTMN** [comment]
> It is self promotion, but you can use my version of the app, WLED Native, to solve the discovery on android
> 
> https://play.google.com/store/apps/details?id=ca.cgagnier.wlednativeandroid https://github.com/Moustachauve/WLED-Native-Android

I have a Galaxy S22 on Android 13 and have the same issue with your native app as well as Aircoookie's app. Discovery mode finds nothing. 
With both WLED and Native I am restricted to entering the IP addresses manually or using AP mode. Thank you for for your app. I do like the native app.
I hope to see advancements with the discovery mode issue in the near future.

**Comment by Moustachauve** [comment]
Do you have mDNS enabled on WLED itself? (In wifi settings)
Does your network have anything out of the ordinary like separate SSID for IoT devices or multiple access points?

**Comment by Aircoookie** [comment]
Finally found time to push an update that should fix this issue to Play, it is still in review.
In the meantime, you may try this APK:
https://drive.google.com/file/d/1m1EfTe7t0T2CRHMsOF9Q91Gk2TlAi9rF/view?usp=sharing

Please let me know whether it fixes the discovery process on Android 13, as I currently do not have access to a phone with that version.

**Comment by Aircoookie** [comment]
The update is now also available on the Play Store :)

**Comment by mjoshd** [comment]
The update seems to have has fixed it 👍

Discovery is now working again on my phone with Android 13.

Thank you so much for your work on this amazing project!
