### ISSUE TITLE
Is the iOS app region locked? 

### ISSUE THREAD

**Issue by selmeczia** [Aircoookie/WLED-App#26]
I can't open the [link ](https://apps.apple.com/us/app/wled/id1475695033) to the official Appstore link of the iOS app as it is just says "Connecting...". I also can't find it in my phone's appstore. Is there a region lock on it? I'm located in Hungary, Europe.

**Comment by Christianst001** [comment]
I’m also unable to find or download the app. currently in Northeast US.

**Comment by DavidIstars** [comment]
Also having this issue.

**Comment by rchpi87** [comment]
Same issue in NorthEast US

**Comment by emanuelrode** [comment]
Same issue in Germany.

**Comment by nanojavi** [comment]
Same issue from Spain

**Comment by jam0ra** [comment]
Same issue from Canada

**Comment by tomjmul** [comment]
Same UK

**Comment by vandy9** [comment]
Same in Southwestern US.  Can anyone respond to when WLED for ios will be available again?

**Comment by aryajuanda** [comment]
its avalable again now
