### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED-App#3]
This issue is to discuss and keep track of the iOS support progress, which may be added later on.

**Comment by MadNBG** [comment]
I hope more features to come. Changing effects, speed etc.

**Comment by Aircoookie** [comment]
Hi! Changing speed and effects is possible. Just click on your WLED device in the app overview list and it will open the usual web UI!

**Comment by 9H5G** [comment]
Hi, WLED is amazing. Thank you. I use on android without problems, mostly. On iPad, the effects list does not scroll. Not urgent. Info only thanks again.

**Comment by tihoangyeudau** [comment]
How can i create ipa ? i just have free apple dev account, i cant create ipa

**Comment by Aircoookie** [comment]
@9H5G thank you! This is fixed in the latest release 0.9.0-b1 :)

@tihoangyeudau I am not sure what IPA is or why you would need to create it. You can just download the app from the store

**Comment by tihoangyeudau** [comment]
> @9H5G thank you! This is fixed in the latest release 0.9.0-b1 :)
> 
> @tihoangyeudau I am not sure what IPA is or why you would need to create it. You can just download the app from the store

I just wanna learn how to make ipa from source code.

**Comment by BenBrochtrup** [comment]
I was wondering if there would ever be support for connecting to unsecured wifi networks on the IOS app. Currently, when you leave the password field empty and click "Save and Connect", it 'saves' and then reverts the password back to whatever it was before it was cleared. Thanks!

**Comment by Aircoookie** [comment]
@BenBrochtrup thank you, reproduced that. Seems like clearing the password indeed does not work.
This is not an issue with the iOS app, but rather with WLED itself. Will fix!
